### ISSUE TITLE
AWS Cloud hierarchy of compute services

### ISSUE THREAD

**Issue by dscoppelletti** [binitauthor/rollingstone-ecommerce-category-k8s-api#1]
Hi Binit,  
The figure in paragraph 3.5 of your book is very small: the labels are too tiny and I can't read them even if I capture the image from the screen and try to zoom it.  
Please, can you share the image?  
Thanks.

**Comment by binitauthor** [comment]
Hi Dario,

Let me draw a new one similar to the one in the book and upload the git repos.

Thanks,

Binit

**Comment by binitauthor** [comment]
Hi Dario,

I have uploaded a new set of architecture diagrams as a .drawio file. Either you can download Draw.io Windows/ Mac OS app or you can also open the diagram in (https://app.diagrams.net/). The diagram files is on the repository root.

Thanks,

Binit

**Comment by dscoppelletti** [comment]
Hi Binit,
I appreciate the your graphic assets, but there was a misunderstanding in which picture is really too small.

I have attacched it here.
<img width="415" alt="physical-structure-of-cloud-data-center" src="https://user-images.githubusercontent.com/7059641/162206569-89019051-ab98-4125-9885-6ac48276b9cb.png">

Thanks.

**Comment by binitauthor** [comment]
Hi Dario,

Sorry for the confusion. In the same code repository , I actually have added the .drawio file that has all the diagrams in much more visible quality. The file name is : 

[AWS_Architecture_Official.drawio](https://github.com/binitauthor/rollingstone-ecommerce-category-k8s-api/blob/main/AWS_Architecture_Official.drawio)

Please clone the repo again and you can open the .drawio file in the windows / manos app or in the website https://app.diagrams.net/

But let me add the picture to the README.md as well.

Thanks,

Binit
